# This is a basic workflow to help you get started with Actions
name: Resharper Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
      - name: Add package 
        run: dotnet add Sender.Tests/Sender.Tests.csproj package xunit --version 2.4.1
      - name: Add package 
        run: dotnet add Receiver.Tests/Receiver.Tests.csproj package xunit --version 2.4.1
      - name: Run resharper inspection
        run: jb inspectcode CaseStudy-S21B7.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder CaseStudy-S21B7.sln -o=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1
